export const wilayas = [
  { id: "01", fr: "Adrar", ar: "أدرار" },
  { id: "02", fr: "Chlef", ar: "الشلف" },
  { id: "03", fr: "Laghouat", ar: "الأغواط" },
  { id: "04", fr: "Oum El Bouaghi", ar: "أم البواقي" },
  { id: "05", fr: "Batna", ar: "باتنة" },
  { id: "06", fr: "Béjaïa", ar: "بجاية" },
  { id: "07", fr: "Biskra", ar: "بسكرة" },
  { id: "08", fr: "Béchar", ar: "بشار" },
  { id: "09", fr: "Blida", ar: "البليدة" },
  { id: "10", fr: "Bouira", ar: "البويرة" },
  { id: "11", fr: "Tamanrasset", ar: "تمنراست" },
  { id: "12", fr: "Tébessa", ar: "تبسة" },
  { id: "13", fr: "Tlemcen", ar: "تلمسان" },
  { id: "14", fr: "Tiaret", ar: "تيارت" },
  { id: "15", fr: "Tizi Ouzou", ar: "تيزي وزو" },
  { id: "16", fr: "Alger", ar: "الجزائر" },
  { id: "17", fr: "Djelfa", ar: "الجلفة" },
  { id: "18", fr: "Jijel", ar: "جيجل" },
  { id: "19", fr: "Sétif", ar: "سطيف" },
  { id: "20", fr: "Saïda", ar: "سعيدة" },
  { id: "21", fr: "Skikda", ar: "سكيكدة" },
  { id: "22", fr: "Sidi Bel Abbès", ar: "سيدي بلعباس" },
  { id: "23", fr: "Annaba", ar: "عنابة" },
  { id: "24", fr: "Guelma", ar: "قالمة" },
  { id: "25", fr: "Constantine", ar: "قسنطينة" },
  { id: "26", fr: "Médéa", ar: "المدية" },
  { id: "27", fr: "Mostaganem", ar: "مستغانم" },
  { id: "28", fr: "M'Sila", ar: "المسيلة" },
  { id: "29", fr: "Mascara", ar: "معسكر" },
  { id: "30", fr: "Ouargla", ar: "ورقلة" },
  { id: "31", fr: "Oran", ar: "وهران" },
  { id: "32", fr: "El Bayadh", ar: "البيض" },
  { id: "33", fr: "Illizi", ar: "إليزي" },
  { id: "34", fr: "Bordj Bou Arreridj", ar: "برج بوعريريج" },
  { id: "35", fr: "Boumerdès", ar: "بومرداس" },
  { id: "36", fr: "El Tarf", ar: "الطارف" },
  { id: "37", fr: "Tindouf", ar: "تندوف" },
  { id: "38", fr: "Tissemsilt", ar: "تيسمسيلت" },
  { id: "39", fr: "El Oued", ar: "الوادي" },
  { id: "40", fr: "Khenchela", ar: "خنشلة" },
  { id: "41", fr: "Souk Ahras", ar: "سوق أهراس" },
  { id: "42", fr: "Tipaza", ar: "تيبازة" },
  { id: "43", fr: "Mila", ar: "ميلة" },
  { id: "44", fr: "Aïn Defla", ar: "عين الدفلى" },
  { id: "45", fr: "Naâma", ar: "النعامة" },
  { id: "46", fr: "Aïn Témouchent", ar: "عين تموشنت" },
  { id: "47", fr: "Ghardaïa", ar: "غرداية" },
  { id: "48", fr: "Relizane", ar: "غليزان" },
  { id: "49", fr: "Timimoun", ar: "تيميمون" },
  { id: "50", fr: "Bordj Badji Mokhtar", ar: "برج باجي مختار" },
  { id: "51", fr: "Ouled Djellal", ar: "أولاد جلال" },
  { id: "52", fr: "Béni Abbès", ar: "بني عباس" },
  { id: "53", fr: "In Salah", ar: "عين صالح" },
  { id: "54", fr: "In Guezzam", ar: "عين قزام" },
  { id: "55", fr: "Touggourt", ar: "توقرت" },
  { id: "56", fr: "Djanet", ar: "جانت" },
  { id: "57", fr: "El M'Ghaier", ar: "المغير" },
  { id: "58", fr: "El Meniaa", ar: "المنيعة" }
];
