export default {
  name: 'product',
  title: 'Produit / منتج',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Nom / الاسم',
      type: 'object',
      fields: [
        { name: 'fr', title: 'Français', type: 'string' },
        { name: 'ar', title: 'العربية', type: 'string' },
      ],
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'name.fr' },
    },
    {
      name: 'description',
      title: 'Description / الوصف',
      type: 'object',
      fields: [
        { name: 'fr', title: 'Français', type: 'text' },
        { name: 'ar', title: 'العربية', type: 'text' },
      ],
    },
    {
      name: 'price',
      title: 'Prix / السعر',
      type: 'number',
    },
    {
      name: 'comparePrice',
      title: 'Prix barré / السعر الأصلي',
      type: 'number',
    },
    {
      name: 'currency',
      title: 'Devise / العملة',
      type: 'string',
      options: {
        list: [
          { title: 'DZD - دينار جزائري', value: 'DZD' },
          { title: 'EUR - يورو', value: 'EUR' },
          { title: 'USD - دولار', value: 'USD' },
        ],
      },
      initialValue: 'DZD',
    },
    {
      name: 'images',
      title: 'Images / الصور',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
    },
    {
      name: 'category',
      title: 'Catégorie / الفئة',
      type: 'reference',
      to: [{ type: 'category' }],
    },
    {
      name: 'sizes',
      title: 'Tailles / المقاسات',
      type: 'array',
      of: [
        {
          type: 'string',
          options: {
            list: [
              { title: 'S', value: 'S' },
              { title: 'M', value: 'M' },
              { title: 'L', value: 'L' },
              { title: 'XL', value: 'XL' },
              { title: 'XXL', value: 'XXL' },
              { title: 'XXXL', value: 'XXXL' },
              { title: '38', value: '38' },
              { title: '40', value: '40' },
              { title: '42', value: '42' },
              { title: '44', value: '44' },
              { title: '46', value: '46' },
              { title: '48', value: '48' },
              { title: '50', value: '50' },
              { title: '52', value: '52' },
              { title: '54', value: '54' },
              { title: '56', value: '56' },
              { title: 'Taille 1', value: 'Taille 1' },
              { title: 'Taille 2', value: 'Taille 2' },
            ],
            layout: 'checkbox',
          },
        },
      ],
    },
    {
      name: 'colors',
      title: 'Couleurs / الألوان',
      type: 'array',
      of: [
        {
          type: 'string',
          options: {
            list: [
              { title: 'Noir / أسود', value: '#000000' },
              { title: 'Blanc / أبيض', value: '#FFFFFF' },
              { title: 'Rouge / أحمر', value: '#FF0000' },
              { title: 'Bleu / أزرق', value: '#0000FF' },
              { title: 'Vert / أخضر', value: '#008000' },
              { title: 'Jaune / أصفر', value: '#FFFF00' },
              { title: 'Orange / برتقالي', value: '#FFA500' },
              { title: 'Violet / بنفسجي', value: '#800080' },
              { title: 'Rose / وردي', value: '#FFC0CB' },
              { title: 'Gris / رمادي', value: '#808080' },
              { title: 'Marron / بني', value: '#8B4513' },
              { title: 'Beige / بيج', value: '#F5F5DC' },
              { title: 'Or / ذهبي', value: '#FFD700' },
              { title: 'Argent / فضي', value: '#C0C0C0' },
              { title: 'Bordeaux / نبيتي', value: '#800020' },
              { title: 'Marine / كحلي', value: '#000080' },
              { title: 'Turquoise / فيروزي', value: '#40E0D0' },
              { title: 'Lavande / لافندر', value: '#E6E6FA' },
              { title: 'Corail / مرجاني', value: '#FF7F50' },
              { title: 'Crème / كريمي', value: '#FFFDD0' },
              { title: 'Kaki / كاكي', value: '#4B5320' },
              { title: 'Pêche / خوخي', value: '#FFCBA4' },
              { title: 'Menthe / نعناعي', value: '#98FF98' },
              { title: 'Ciel / سماوي', value: '#87CEEB' },
              { title: 'Émeraude / زمردي', value: '#50C878' },
              { title: 'Rubis / ياقوتي', value: '#E0115F' },
              { title: 'Saphir / ياقوتي أزرق', value: '#0F52BA' },
              { title: 'Ivoire / عاجي', value: '#FFFFF0' },
              { title: 'Charbon / فحمي', value: '#36454F' },
              { title: 'Prune / بруني', value: '#701C1C' },
              { title: 'Fuchsia / فوشيا', value: '#FF00FF' },
              { title: 'Saumon / سلموني', value: '#FA8072' },
              { title: 'Moutarde / خردلي', value: '#FFDB58' },
              { title: 'Olive / زيتوني', value: '#808000' },
              { title: 'Cognac / كونياك', value: '#9A463D' },
              { title: 'Poudre / بودري', value: '#FADADD' },
              { title: 'Pétrole / بترولي', value: '#005F64' },
              { title: 'Noisette / بندق', value: '#9A7142' },
              { title: 'Amande / لوزي', value: '#EED9C4' },
              { title: 'Lilas / ليلكي', value: '#C8A2C8' },
            ],
            layout: 'checkbox',
          },
        },
      ],
    },
    {
      name: 'variants',
      title: 'Variantes / المتغيرات (اللون + المقاس + الكمية)',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'color',
              title: 'Couleur / اللون',
              type: 'string',
              options: {
                list: [
                  { title: 'Noir / أسود', value: '#000000' },
                  { title: 'Blanc / أبيض', value: '#FFFFFF' },
                  { title: 'Rouge / أحمر', value: '#FF0000' },
                  { title: 'Bleu / أزرق', value: '#0000FF' },
                  { title: 'Vert / أخضر', value: '#008000' },
                  { title: 'Jaune / أصفر', value: '#FFFF00' },
                  { title: 'Orange / برتقالي', value: '#FFA500' },
                  { title: 'Violet / بنفسجي', value: '#800080' },
                  { title: 'Rose / وردي', value: '#FFC0CB' },
                  { title: 'Gris / رمادي', value: '#808080' },
                  { title: 'Marron / بني', value: '#8B4513' },
                  { title: 'Beige / بيج', value: '#F5F5DC' },
                  { title: 'Or / ذهبي', value: '#FFD700' },
                  { title: 'Argent / فضي', value: '#C0C0C0' },
                  { title: 'Bordeaux / نبيتي', value: '#800020' },
                  { title: 'Marine / كحلي', value: '#000080' },
                  { title: 'Turquoise / فيروزي', value: '#40E0D0' },
                  { title: 'Lavande / لافندر', value: '#E6E6FA' },
                  { title: 'Corail / مرجاني', value: '#FF7F50' },
                  { title: 'Crème / كريمي', value: '#FFFDD0' },
                  { title: 'Kaki / كاكي', value: '#4B5320' },
                  { title: 'Pêche / خوخي', value: '#FFCBA4' },
                  { title: 'Menthe / نعناعي', value: '#98FF98' },
                  { title: 'Ciel / سماوي', value: '#87CEEB' },
                  { title: 'Émeraude / زمردي', value: '#50C878' },
                  { title: 'Rubis / ياقوتي', value: '#E0115F' },
                  { title: 'Saphir / ياقوتي أزرق', value: '#0F52BA' },
                  { title: 'Ivoire / عاجي', value: '#FFFFF0' },
                  { title: 'Charbon / فحمي', value: '#36454F' },
                  { title: 'Prune / بруني', value: '#701C1C' },
                  { title: 'Fuchsia / فوشيا', value: '#FF00FF' },
                  { title: 'Saumon / سلموني', value: '#FA8072' },
                  { title: 'Moutarde / خردلي', value: '#FFDB58' },
                  { title: 'Olive / زيتوني', value: '#808000' },
                  { title: 'Cognac / كونياك', value: '#9A463D' },
                  { title: 'Poudre / بودري', value: '#FADADD' },
                  { title: 'Pétrole / بترولي', value: '#005F64' },
                  { title: 'Noisette / بندق', value: '#9A7142' },
                  { title: 'Amande / لوزي', value: '#EED9C4' },
                  { title: 'Lilas / ليلكي', value: '#C8A2C8' },
                ],
              },
            },
            {
              name: 'size',
              title: 'Taille / المقاس',
              type: 'string',
              options: {
                list: [
                  { title: 'S', value: 'S' },
                  { title: 'M', value: 'M' },
                  { title: 'L', value: 'L' },
                  { title: 'XL', value: 'XL' },
                  { title: 'XXL', value: 'XXL' },
                  { title: 'XXXL', value: 'XXXL' },
                  { title: '38', value: '38' },
                  { title: '40', value: '40' },
                  { title: '42', value: '42' },
                  { title: '44', value: '44' },
                  { title: '46', value: '46' },
                  { title: '48', value: '48' },
                  { title: '50', value: '50' },
                  { title: '52', value: '52' },
                  { title: '54', value: '54' },
                  { title: '56', value: '56' },
                  { title: 'Taille 1', value: 'Taille 1' },
                  { title: 'Taille 2', value: 'Taille 2' },
                ],
              },
            },
            {
              name: 'quantity',
              title: 'Quantité / الكمية',
              type: 'number',
              validation: (Rule: any) => Rule.min(0).integer(),
            },
            {
              name: 'lowStockThreshold',
              title: 'Seuil d\'alerte / حد التنبيه',
              type: 'number',
              description: 'Alerte quand la quantité atteint ce seuil / تنبيه عند وصول الكمية لهذا الحد',
              validation: (Rule: any) => Rule.min(0).integer(),
              initialValue: 5,
            },
          ],
          preview: {
            select: {
              color: 'color',
              size: 'size',
              quantity: 'quantity',
              threshold: 'lowStockThreshold',
            },
            prepare({ color, size, quantity, threshold }: { color: string; size: string; quantity: number; threshold: number }) {
              const stockStatus = quantity === 0 ? '❌ Rupture' : 
                                 quantity <= (threshold || 5) ? '⚠️ Stock bas' : 
                                 '✅ En stock';
              return {
                title: `${color || 'N/A'} - ${size || 'N/A'}`,
                subtitle: `${stockStatus} (${quantity || 0})`,
              };
            },
          },
        },
      ],
    },
    {
      name: 'isFeatured',
      title: 'Produit vedette / منتج مميز',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'isNew',
      title: 'Nouveau / جديد',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'isSale',
      title: 'En solde / تخفيض',
      type: 'boolean',
      initialValue: false,
    },
  ],
  preview: {
    select: {
      title: 'name.fr',
      media: 'images.0',
    },
  },
};
